version: 2
updates:
- package-ecosystem: gradle
  directory: "/loader"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/plugin"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
