#!/usr/bin/python3
"""
Filename: MiraiCP/cpp/include/addinclude.py
Path: MiraiCP/cpp/include
Author: 1930893235@qq.com
Copyright (c) 2021 Eritque arcus
"""
import os
import re

ss = """// This file is generated automatically by a building script;
// When contributing to this repository, please DO NOT edit this file.

// Copyright (C) 2020-2021 Eritque arcus and contributors.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or any later version(in your opinion).
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""

ss += "#include <MiraiCP.hpp>\n"

for filename in sorted(os.listdir('include')):
    if filename.endswith('.cpp'):
        ss += "//from " + filename + "\n" \
              + re.sub(r"#include \"(.*)\"", "",
                       open(
                           "include/" + filename, 'r',
                           encoding="utf-8"
                       ).read()
                       )

open('single_include/MiraiCP/MiraiCP.cpp', 'w', encoding='utf-8').write(ss)
print("header file generated successfully")
