/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_mirai_plugin_CPP_lib */

#ifndef _Included_org_example_mirai_plugin_CPP_lib
#define _Included_org_example_mirai_plugin_CPP_lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_mirai_plugin_CPP_lib
 * Method:    Verify
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_mirai_plugin_CPP_1lib_Verify
  (JNIEnv *, jobject);

/*
 * Class:     org_example_mirai_plugin_CPP_lib
 * Method:    Event
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_mirai_plugin_CPP_1lib_Event
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_example_mirai_plugin_CPP_lib
 * Method:    PluginDisable
 * Signature: ()Ljava/lang/Void;
 */
JNIEXPORT jobject JNICALL Java_org_example_mirai_plugin_CPP_1lib_PluginDisable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
