/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_mirai_plugin_CPP_lib_Companion */

#ifndef _Included_org_example_mirai_plugin_CPP_lib_Companion
#define _Included_org_example_mirai_plugin_CPP_lib_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
