/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tech_eritquearcus_miraicp_CPP_lib_Companion */

#ifndef _Included_tech_eritquearcus_miraicp_CPP_lib_Companion
#define _Included_tech_eritquearcus_miraicp_CPP_lib_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
