name: Bug Report
description: 提交一份错误报告
labels: ["t:question"]
body:
  - type: checkboxes
    id: preCheck
    attributes:
      label: Code of Conduct
      description: |
        Thank for reporting!
        在提交前请确保做完以下的检查:
        - 没有相同内容/类型issue
        - 中间件, 启动器, SDK依赖已经更新到最新版
        - 我确认不是产生了自己导致的编译问题,包括:
          - 不是尝试在Linux上使用.dll文件或者Windows上使用.so文件等
          - 生成的动态链接库与使用的jdk均为64位, jdk版本>=11
          - 在同一台计算机上编译并使用或已经自行保证了可移植性
        - By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Nambers/MiraiCP/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I conform
          required: true
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 描述遇到的问题(预期效果和目前效果)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志
      description: 日志文本
      render: text
  - type: input
    id: version
    attributes:
      label: 版本
      description: 发生在哪个版本上
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: 组件
      description: 发生在哪个组件上
      multiple: true
      options:
        - Loader
        - Plugin
        - LibLoader
    validations:
      required: true
