// Copyright (C) 2020-2021 Eritque arcus and contributors.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or any later version(in your opinion).
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tech_eritquearcus_miraicp_shared_CPP_lib */

#ifndef _Included_tech_eritquearcus_miraicp_shared_CPP_lib
#define _Included_tech_eritquearcus_miraicp_shared_CPP_lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tech_eritquearcus_miraicp_shared_CPP_lib
 * Method:    Verify
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tech_eritquearcus_miraicp_shared_CPP_1lib_Verify
  (JNIEnv *, jobject);

/*
 * Class:     tech_eritquearcus_miraicp_shared_CPP_lib
 * Method:    Event
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tech_eritquearcus_miraicp_shared_CPP_1lib_Event
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tech_eritquearcus_miraicp_shared_CPP_lib
 * Method:    PluginDisable
 * Signature: ()Ljava/lang/Void;
 */
JNIEXPORT jobject JNICALL Java_tech_eritquearcus_miraicp_shared_CPP_1lib_PluginDisable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
