name: C++ CI in windows

on: 
  push:
    branches: [ master ]
    paths:
      - "cpp/**"
  pull_request:
    branches: [ master ]
    paths:
      - "cpp/**"
  workflow_dispatch:

jobs:
  windows-msvc-single:
    runs-on: windows-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
    - name: configure
      run: mkdir cpp/build && cd cpp/build && cmake ..
    - name: build with msvc
      run: cd ./cpp && cmake --build build --config Debug --target generateSingleHeader && cmake --build build --config Debug --target MiraiCP_single
  windows-mingw:
    runs-on: windows-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
    - name: configure
      env: 
        cc: gcc
        cxx: g++
      run: mkdir cpp/build && cd cpp/build && cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - MinGW Makefiles" ..
    - name: build with gcc
      run: cd ./cpp && cmake --build build --config Debug --target generateSingleHeader && cmake --build build --config Debug --target MiraiCP_single
