name: C++ CI in windows & linux

on: 
  push:
    branches:
      - '*'
    paths:
      - "cpp/**"
  pull_request:
    branches:
      - '*'
    paths:
      - "cpp/**"
  workflow_dispatch:

jobs:
  ubuntu-mingw:
    runs-on: ubuntu-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
    - name: configure
      env: 
        cc: gcc
        cxx: g++
      run: mkdir cpp/build && cd cpp/build && cmake ..
    - name: build with gcc
      run: cd cpp/build && make generateSingleHeaders && make MiraiCP_single
  windows-msvc-single:
    runs-on: windows-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
    - name: configure
      run: mkdir cpp/build && cd cpp/build && cmake ..
    - name: build with msvc
      run: cd ./cpp && cmake --build build --config Debug --target generateSingleHeaders && cmake --build build --config Debug --target MiraiCP_single
  windows-mingw:
    runs-on: windows-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
    - name: configure
      env: 
        cc: gcc
        cxx: g++
      run: mkdir cpp/build && cd cpp/build && cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - MinGW Makefiles" ..
    - name: build with gcc
      run: cd ./cpp && cmake --build build --config Debug --target generateSingleHeaders && cmake --build build --config Debug --target MiraiCP_single
