name: C++ CI in windows & linux

on: 
  push:
    branches:
      - '*'
    paths:
      - "cpp/**"
  pull_request:
    branches:
      - '*'
    paths:
      - "cpp/**"
  workflow_dispatch:

jobs:
  ubuntu-gcc-single:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: configure
      env:
        cc: gcc
        cxx: g++
      run: mkdir cpp/build && cd cpp/build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build with gcc
      run: cd cpp/build && make generateSingleHeaders && make MiraiCP_single
  windows-msvc-single:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: configure
      run: mkdir cpp/build && cd cpp/build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build with msvc
      run: cd ./cpp && cmake --build build --target generateSingleHeaders && cmake --build build --target MiraiCP_single
  windows-mingw-single:
    runs-on: windows-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
    - name: configure
      env:
        cc: gcc
        cxx: g++
      run: mkdir cpp/build && cd cpp/build && cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - MinGW Makefiles" ..
    - name: build with gcc
      run: cd ./cpp && cmake --build build --target generateSingleHeaders && cmake --build build --target MiraiCP_single
  ubuntu-gcc-core:
    runs-on: ubuntu-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
    - name: configure
      env:
        cc: gcc
        cxx: g++
      run: mkdir cpp/build && cd cpp/build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build with gcc
      run: cd cpp/build && make MiraiCP_core
  windows-mingw-libLoader:
    runs-on: windows-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
    - name: configure
      env:
        cc: gcc
        cxx: g++
      run: mkdir cpp/build && cd cpp/build && cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - MinGW Makefiles" ..
    - name: build with gcc
      run: cd ./cpp && cmake --build build --target Loader
  ubuntu-gcc-libLoader:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: configure
      env:
        cc: gcc
        cxx: g++
      run: mkdir cpp/build && cd cpp/build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build with gcc
      run: cd cpp/build && make Loader
