name: C++ CI in windows & linux

on: 
  push:
    branches:
      - '*'
    paths:
      - "cpp/**"
  pull_request:
    branches:
      - '*'
    paths:
      - "cpp/**"
  workflow_dispatch:

jobs:
  single:
    name: "build MiraiCP-single (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-latest
        include:
          - os: windows-2019
            targetName: MSVCX64
          - os: ubuntu-latest
            targetName: LinuxX64
    env:
      isWindows: ${{ startsWith(matrix.os, 'windows') }}
      isUbuntu: ${{ startsWith(matrix.os, 'ubuntu') }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: mkdir cpp/build && cd cpp/build && cmake -DCMAKE_BUILD_TYPE=Release -DGOOGLE_TEST=OFF ..
      # Linux
      - name: setup gcc
        if: ${{ env.isUbuntu == 'true' }}
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64
      - name: build with gcc ubuntu
        if: ${{ env.isUbuntu == 'true' }}
        env:
          cc: gcc
          cxx: g++
        run: cd cpp/build && make generateSingleHeaders && make MiraiCP_single
      # Windows
      - name: setup MSVC
        if: ${{ env.isWindows == 'true' }}
        uses: ilammy/msvc-dev-cmd@v1.12.0
        with:
          arch: amd64
          vsversion: 2019
      - name: build with MSVC
        if: ${{ env.isWindows == 'true' }}
        run: cd ./cpp && cmake --build build --target generateSingleHeaders && cmake --build build --target MiraiCP_single --config Release

  windows-mingw-single:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: mkdir cpp/build && cd cpp/build && cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - MinGW Makefiles" -DGOOGLE_TEST=OFF ..
      - name: build with MinGW
        run: cd ./cpp && cmake --build build --target generateSingleHeaders && cmake --build build --target MiraiCP_single

  libLoader:
    name: "build MiraiCP-libLoader (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-latest
        include:
          - os: windows-2019
            targetName: MSVCX64
          - os: ubuntu-latest
            targetName: linuxX64
    env:
      isWindows: ${{ startsWith(matrix.os, 'windows') }}
      isUbuntu: ${{ startsWith(matrix.os, 'ubuntu') }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        
        run: mkdir cpp/build && cd cpp/build && cmake -DCMAKE_BUILD_TYPE=Release -DGOOGLE_TEST=OFF ..

      - name: setup gcc
        if: ${{ env.isUbuntu == 'true' }}
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64
      - name: build with gcc ubuntu
        if: ${{ env.isUbuntu == 'true' }}
        env:
          cc: gcc
          cxx: g++
        run: cd cpp/build && make Loader
      
      - name: setup MSVC
        if: ${{ env.isWindows == 'true' }}
        uses: ilammy/msvc-dev-cmd@v1.12.0
        with:
          arch: amd64
          vsversion: 2019
      - name: build with MSVC
        if: ${{ env.isWindows == 'true' }}
        run: cd ./cpp && cmake --build build --config Release --target Loader

  libLoader-native:
    name: "build Native (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        include:
          - os: windows-latest
            targetName: mingwX64
          - os: ubuntu-latest
            targetName: linuxX64
    env:
      isWindows: ${{ startsWith(matrix.os, 'windows') }}
      isUbuntu: ${{ startsWith(matrix.os, 'ubuntu') }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: mkdir cpp/build && cd cpp/build && cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - MinGW Makefiles" -DGOOGLE_TEST=OFF ..

      - name: setup gcc
        if: ${{ env.isUbuntu == 'true' }}
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64
      - if: ${{ env.isUbuntu == 'true' }}
        name: build with gcc ubuntu
        env:
          cc: gcc
          cxx: g++
        run: cd cpp/build && make LoaderNative
      
      - if: ${{ env.isWindows == 'true' }}
        name: build with MinGW win
        run: cd cpp && cmake --build build --target LoaderNative
