# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
 push:
    branches: [ master ]
    paths:
      - "kotlin/**"
 pull_request:
    branches: [ master ]
    paths:
      - "kotlin/**"
 workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
#     - name: Cache Gradle packages
#       uses: actions/cache@v2
#       with:
#        path: |
#          ./kotlin/.gradle
#        key: ${{ runner.os }}-build-${{ env.cache-name }}
#     - name: Set up JDK 15
#       uses: actions/setup-java@v2
#       with:
#         java-version: '15'
#         distribution: 'adopt'
    - name: chmod -R 777 *
      run: chmod -R 777 *
    - name: Build loader
      run:  cd ./kotlin/ && ./gradlew MiraiCP-loader:shadowJar --warning-mode all --info --stacktrace
    - name: Build plugin
      run:  cd ./kotlin/ && ./gradlew MiraiCP-plugin:buildPlugin --warning-mode all --info --stacktrace
