name: loadTest

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  windows-load-test:
    runs-on: windows-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
    - name: chmod -R 777 *
      run: chmod -R 777 *
    - name: configure
      run: mkdir "cpp/cmake-build-debug" && cd "cpp/cmake-build-debug" && cmake -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles" ..
    - name: complie cpp
      run: cd ./cpp && cmake --build "cmake-build-debug" --target Loader && cmake --build "cmake-build-debug" --target MiraiCP_multi
    - name: tree
      run: tree /f
    - name: loadTest
      run: cd ./kotlin/ && ./gradlew :MiraiCP-loader:test --tests "tech.eritquearcus.miraicp.loader.LoaderCITest.test" --warning-mode all --info --stacktrace

  ubuntu-load-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
    - name: chmod -R 777 *
      run: chmod -R 777 *
    - name: configure
      env:
        cc: gcc
        cxx: g++
      run: mkdir "cpp/cmake-build-debug" && cd "cpp/cmake-build-debug" && cmake -DCMAKE_BUILD_TYPE=Release .. && make Loader && make MiraiCP_multi
    - name: loadTest
      run:  cd ./kotlin/ && ./gradlew :MiraiCP-loader:test --tests "tech.eritquearcus.miraicp.loader.LoaderCITest.test" --warning-mode all --info --stacktrace
