name: loadTest

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  windows-load-test:
    runs-on: windows-2019
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
    - name: chmod -R 777 *
      run: chmod -R 777 *
    - name: setup MSVC
      uses: ilammy/msvc-dev-cmd@v1.12.0
      with:
        arch: amd64
        vsversion: 2019
    - name: configure
      run: mkdir "cpp/cmake-build-debug" && cd "cpp/cmake-build-debug" && cmake -DCMAKE_BUILD_TYPE=Release -DGOOGLE_TEST=OFF ..
    - name: complie cpp
      run: cd ./cpp && cmake --build "cmake-build-debug" --config Release --target Loader && cmake --build "cmake-build-debug" --config Release --target MiraiCP_multi
    - name: tree
      run: tree /f
    - name: loadTest
      run: cd ./kotlin/ && ./gradlew :MiraiCP-loader:test --tests "tech.eritquearcus.miraicp.loader.LoaderCITest.test" --warning-mode all --info --stacktrace

  ubuntu-load-test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
    - name: chmod -R 777 *
      run: chmod -R 777 *
    - name: setup gcc
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 9
        platform: x64
    - name: configure
      env:
        cc: gcc
        cxx: g++
      run: mkdir "cpp/cmake-build-debug" && cd "cpp/cmake-build-debug" && cmake -DCMAKE_BUILD_TYPE=Release -DGOOGLE_TEST=OFF .. && make Loader && make MiraiCP_multi
    - name: loadTest
      run:  cd ./kotlin/ && ./gradlew :MiraiCP-loader:test --tests "tech.eritquearcus.miraicp.loader.LoaderCITest.test" --warning-mode all --info --stacktrace
