name: Kotlin MPP Native CI with Gradle

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - "kotlin/loader/**"
      - "kotlin/shared/**"
      - "cpp/src/**"
      - ".github/workflows/native.yml"
  pull_request:
    branches:
      - '*'
    paths:
      - "kotlin/loader/**"
      - "kotlin/shared/**"
      - "cpp/src/**"
      - ".github/workflows/native.yml"

jobs:
  no-job:
    if: "!contains(github.event.commits[0].message, 'native')"
    runs-on: ubuntu-20.04
    steps:
      - name: nope
        run: echo "hi"

  libLoader-native:
    name: "build libLoader-native (${{ matrix.os }})"
    if: "contains(github.event.commits[0].message, 'native')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-20.04
        include:
          - os: windows-latest
            targetName: mingwX64
          - os: ubuntu-20.04
            targetName: linuxX64
    env:
      isWindows: ${{ startsWith(matrix.os, 'windows') }}
      isUbuntu: ${{ startsWith(matrix.os, 'ubuntu') }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: build with gcc ubuntu
      if: ${{ env.isUbuntu == 'true' }}
      env:
        cc: gcc
        cxx: g++
      run: ./scripts/LINUX/cppBuilds.sh libLoaderNative
    
    - name: build with gcc win
      if: ${{ env.isWindows == 'true' }}
      env:
        cc: gcc
        cxx: g++
      run: ./scripts/WIN/cppBuilds.bat libLoaderNative
    
    - name: upload
      if: ${{ env.isWindows == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: libLoaderNativeWin
        path: ./cpp/build/
    - name: upload
      if: ${{ env.isUbuntu == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: libLoaderNativeLinux
        path: ./cpp/build/

  build-native:
    name: "build Native (${{ matrix.os }})"
    if: "contains(github.event.commits[0].message, 'native')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-20.04
        include:
          - os: windows-latest
            targetName: mingwX64
          - os: ubuntu-20.04
            targetName: linuxX64
    env:
      isWindows: ${{ startsWith(matrix.os, 'windows') }}
      isUbuntu: ${{ startsWith(matrix.os, 'ubuntu') }}
      VCPKG_DEFAULT_BINARY_CACHE: ${{ startsWith(matrix.os, 'windows') && 'C:\vcpkg\binary_cache' || '/usr/local/share/vcpkg/binary_cache' }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}

    - name: Cache konan
      uses: pat-s/always-upload-cache@v3
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Prepare to cache vcpkg
      if: ${{ env.isWindows == 'true' }}
      run: mkdir -p ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}

    - name: Cache vcpkg
      if: ${{ env.isWindows == 'true' }}
      uses: pat-s/always-upload-cache@v3
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: ${{ runner.os }}-vcpkg-binary-cache-${{ github.job }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-binary-cache-

    - name: Install OpenSSL on Ubuntu
      if: ${{ env.isUbuntu == 'true' }}
      run: sudo apt install libssl-dev -y

    # Prepare environment for linking on Windows
    - name: Setup Memory Environment on Windows
      if: ${{ env.isWindows == 'true' }}
      run: >
        wmic pagefileset where name="D:\\pagefile.sys" set InitialSize=1024,MaximumSize=9216
      shell: cmd
      continue-on-error: true

    - name: Install OpenSSL & cURL on Windows
      if: ${{ env.isWindows == 'true' }}
      run: |
        echo "set(VCPKG_BUILD_TYPE release)" | Out-File -FilePath "$env:VCPKG_INSTALLATION_ROOT\triplets\x64-windows.cmake" -Encoding utf8 -Append
        vcpkg install openssl:x64-windows curl[core,ssl]:x64-windows
        New-Item -Path $env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib\crypto.lib -ItemType SymbolicLink -Value $env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib\libcrypto.lib
        New-Item -Path $env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib\ssl.lib -ItemType SymbolicLink -Value $env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib\libssl.lib
        New-Item -Path $env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib\curl.lib -ItemType SymbolicLink -Value $env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib\libcurl.lib
        echo "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: chmod
      if: ${{ env.isUbuntu == 'true' }}
      run: chmod -R 777 *
    - name: replace def file
      uses: Nambers/ReplaceStringInFile@v1.3
      with:
        path: ${{ github.workspace }}/kotlin/shared/src/nativeInterop/cinterop/localMiraiCP.def
        oldString: GITHUB_WORKSPACE
        newString: ${{ github.workspace }}
        escapeBackslash: true
        showFileContent: true
    # - name: replace MiraiCP lib path of def file linux
    #   if: ${{ env.isUbuntu == 'true' }}
    #   run: sed -i 's|GITHUB_WORKSPACE|${{ github.workspace }}|g' '${{ github.workspace }}/kotlin/shared/src/nativeInterop/cinterop/localMiraiCP.def' && cat ${{ github.workspace }}/kotlin/shared/src/nativeInterop/cinterop/localMiraiCP.def
    # - name: replace MiraiCP lib path of def file win
    #   if: ${{ env.isWindows == 'true' }}
    #   run: $path = "${{ github.workspace }}"; $path=$path.Replace("`\", "/"); (Get-Content ${{ github.workspace }}\kotlin\shared\src\nativeInterop\cinterop\localMiraiCP.def) -replace 'GITHUB_WORKSPACE', $path | Set-Content -encoding ASCII ${{ github.workspace }}\kotlin\shared\src\nativeInterop\cinterop\localMiraiCP.def && type ${{ github.workspace }}/kotlin/shared/src/nativeInterop/cinterop/localMiraiCP.def
    - name: compile native
      run:  cd ./kotlin/ && ./gradlew MiraiCP-loader:compileKotlinNative --warning-mode all --info --stacktrace
    - name: libLoaderNativeWin
      if: ${{ env.isWindows == 'true' }}
      uses: actions/download-artifact@v3
      with:
        name: libLoaderNativeWin
        path: ${{ github.workspace }}
    - name: libLoaderNativeLinux
      if: ${{ env.isUbuntu == 'true' }}
      uses: actions/download-artifact@v3
      with:
        name: libLoaderNativeLinux
        path: ${{ github.workspace }}
    # - if: ${{ env.isWindows == 'true' }}
    #   name: rename libLoader win
    #   run: Rename-Item -Path "${{ github.workspace }}\libLoaderNative.lib" -NewName "LoaderNative.lib"
    - name: link native
      run:  cd ./kotlin/ && ./gradlew MiraiCP-loader:linkDebugExecutableNative --warning-mode all --info --stacktrace