name: "create release"

on:
 workflow_dispatch:
  inputs:
   v:
    required: true
    description: version tag
   pre:
    required: true
    description: pre-release
   notHppAndCpp:
    required: false
    description: Do not contain hpp and cpp file

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
       path: ./kotlin/.gradle
       key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: chmod -R 777 *
      run: chmod -R 777 *
    - name: Build loader
      run:  cd ./kotlin/ && ./gradlew MiraiCP-loader:shadowJar --warning-mode all --info --stacktrace
    - name: Build plugin
      run:  cd ./kotlin/ && ./gradlew MiraiCP-plugin:buildPlugin --warning-mode all --info --stacktrace
    - name: pack
      run:  zip -r ./cpp/MiraiCP_CPP.zip ./cpp
    - name: get change log
      run: "grep -n -i \"## v\" CHANGELOG.md | head -n2 | cut -d: -f1 >> line.tmp"
    - name: get change log2
      run: cat CHANGELOG.md | head -n $((`tail -n 1 line.tmp`-1)) | tail -n +`head -n 1 line.tmp` >> release.log
    - name: show
      run: cat release.log
    - name: generate release files list
      run: |
           if [ ${{ github.event.inputs.notHppAndCpp }} == false ]
           then
            echo "flist=./kotlin/loader/build/libs/MiraiCP-loader-*.jar,./kotlin/plugin/build/mirai/MiraiCP-plugin-*.mirai.jar,./cpp/MiraiCP_CPP.zip,./cpp/include/miraiCP.hpp,./cpp/include/miraiCP.cpp" >> $GITHUB_ENV
            echo "flist=./kotlin/loader/build/libs/MiraiCP-loader-*.jar,./kotlin/plugin/build/mirai/MiraiCP-plugin-*.mirai.jar,./cpp/MiraiCP_CPP.zip,./cpp/include/miraiCP.hpp,./cpp/include/miraiCP.cpp"
           else
            echo "flist=./kotlin/loader/build/libs/MiraiCP-loader-*.jar,./kotlin/plugin/build/mirai/MiraiCP-plugin-*.mirai.jar,./cpp/MiraiCP_CPP.zip" >> $GITHUB_ENV
            echo "flist=./kotlin/loader/build/libs/MiraiCP-loader-*.jar,./kotlin/plugin/build/mirai/MiraiCP-plugin-*.mirai.jar,./cpp/MiraiCP_CPP.zip"
           fi
    - name: Create Release
      uses: ncipollo/release-action@v1.8.6
      with:
          artifacts: ${{ env.flist }}
          bodyfile: release.log
          tag: ${{ github.event.inputs.v }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ github.event.inputs.pre }}
