name: "create release"

on:
 workflow_dispatch:
  inputs:
   v:
    required: true
    description: version tag
   pre:
    required: true
    description: pre-release

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: checkout
      uses: actions/checkout@v2
      with:
       path: template
       repository: Nambers/MiraiCP-template
       ref: main
       persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
       fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
       path: ./kotlin/.gradle
       key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: generate single headers
      env: 
        cc: gcc
        cxx: g++
      run: mkdir cpp/build && cd cpp/build && cmake ..
    - name: build with gcc
      run: cd cpp/build && make generateSingleHeader && make MiraiCP_single
    - name: replace single header
      run: cat cpp/single_include/MiraiCP.hpp > template/singlue_include/MiraiCP.hpp && cat cpp/single_include/MiraiCP.cpp > template/singlue_include/MiraiCP.cpp
    - name: Push
      uses: s0/git-publish-subdir-action@develop 
      env:
        REPO: git@github.com:Nambers/MiraiCP-template.git
        BRANCH: main # The branch name where you want to push the assets
        FOLDER: template # The directory where your assets are generated
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        MESSAGE: ${{ github.event.inputs.v }} # The commit message
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: chmod -R 777 *
      run: chmod -R 777 *
    - name: Build loader
      run:  cd ./kotlin/ && ./gradlew MiraiCP-loader:shadowJar --warning-mode all --info --stacktrace
    - name: Build plugin
      run:  cd ./kotlin/ && ./gradlew MiraiCP-plugin:buildPlugin --warning-mode all --info --stacktrace
    - name: get change log
      run: "grep -n -i \"## v\" CHANGELOG.md | head -n2 | cut -d: -f1 >> line.tmp"
    - name: get change log2
      run: cat CHANGELOG.md | head -n $((`tail -n 1 line.tmp`-1)) | tail -n +`head -n 1 line.tmp` >> release.log
    - name: show
      run: cat release.log
    - name: Create Release
      uses: ncipollo/release-action@v1.8.6
      with:
          artifacts: ./kotlin/loader/build/libs/MiraiCP-loader-*.jar,./kotlin/plugin/build/mirai/MiraiCP-plugin-*.mirai.jar
          bodyfile: release.log
          tag: ${{ github.event.inputs.v }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ github.event.inputs.pre }}
