name: "tempRelease"

on:
 workflow_dispatch:
  inputs:
   v:
      required: true
      description: version tag
   clean:
     required: false
     description: clean all dev release

jobs:
  clean:
    if: ${{ github.event.inputs.clean }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
       persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
       fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: prepare
      run: mkdir ./cleanTr
    - name: Push
      uses: s0/git-publish-subdir-action@develop 
      env:
        REPO: git@github.com:Nambers/MiraiCP-devReleases.git
        BRANCH: main # The branch name where you want to push the assets
        FOLDER: cleanTr # The directory where your assets are generated
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        MESSAGE: "clean all" # The commit message
      
  tempRelease:
    if: ${{ !github.event.inputs.clean }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
       path: main
       persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
       fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: checkout
      uses: actions/checkout@v2
      with:
       path: tr
       repository: Nambers/MiraiCP-devReleases
       ref: main
       persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
       fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: chmod -R 777 *
      run: chmod -R 777 *
    - name: gradlew build
      run: cd ./main/kotlin/ && ./gradlew build
    - name: Build plugin
      run:  cd ./main/kotlin/ && ./gradlew MiraiCP-plugin:buildPlugin --warning-mode all --info --stacktrace
    - name: Build core
      run:  cd ./main/kotlin/ && ./gradlew MiraiCP-core:shadowJar --warning-mode all --info --stacktrace
    - name: Build loader
      run:  cd ./main/kotlin/ && ./gradlew MiraiCP-loader:shadowJar --warning-mode all --info --stacktrace
    - name: configure
      env: 
        cc: gcc
        cxx: g++
      run: mkdir ./main/cpp/build && cd ./main/cpp/build && cmake ..
    - name: build with gcc
      run: cd ./main/cpp/build && make generateSingleHeaders
    - name: moveCPP
      run: rm -rf ./tr/${{ github.event.inputs.v }} && mkdir ./tr/${{ github.event.inputs.v }} && mv "./main/cpp/src/single_include/MiraiCP/MiraiCP.hpp" ./tr/${{ github.event.inputs.v }} && mv "./main/cpp/src/single_include/MiraiCP/MiraiCP.cpp" ./tr/${{ github.event.inputs.v }} && mv "./main/cpp/src/miraicp-core/core.cpp" ./tr/${{ github.event.inputs.v }} && mv "./main/cpp/src/miraicp-core/core.h" ./tr/${{ github.event.inputs.v }}
    - name: moveKt
      run: ls -1 ./main/kotlin/loader/build/libs/MiraiCP-loader-*.jar | xargs -L1 -I{} mv {} ./tr/${{ github.event.inputs.v }} && ls -1 ./main/kotlin/plugin/build/libs/MiraiCP-plugin-*.mirai.jar | xargs -L1 -I{} mv {} ./tr/${{ github.event.inputs.v }} && ls -1 ./main/kotlin/core/build/libs/MiraiCP-core-*.jar | xargs -L1 -I{} mv {} ./tr/${{ github.event.inputs.v }}
    #name: print
     # run: find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
    - name: mv
      run: mv ./tr/.git/ ./.git
    - name: Push
      uses: s0/git-publish-subdir-action@develop 
      env:
        REPO: git@github.com:Nambers/MiraiCP-devReleases.git
        BRANCH: main # The branch name where you want to push the assets
        FOLDER: tr # The directory where your assets are generated
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        MESSAGE: "release dev package: ({sha})" # The commit message
